<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ngs_approve_request"
 *
 * Auto generated by Extension Builder 2019-10-31
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Ngs Approve Request',
    'description' => 'Ngs Approve Request',
    'category' => 'templates',
    'author_company' => 'Naghashyan Solutions LLC',
    'version' => '1.0.0',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-11.5.27',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
