<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'FluidTYPO3\\Vhs\\' => array($typo3InstallDir . 'typo3conf/ext/vhs/Classes'),
    'FriendsOfTYPO3\\FontawesomeProvider\\' => array($typo3InstallDir . 'typo3conf/ext/fontawesome_provider/Classes'),
    'Ig\\IgLanguageDetection\\' => array($typo3InstallDir . 'typo3conf/ext/ig_language_detection/Classes'),
    'Lavitto\\FormToDatabase\\' => array($typo3InstallDir . 'typo3conf/ext/form_to_database/Classes'),
    'Lemming\\Imageoptimizer\\' => array($typo3InstallDir . 'typo3conf/ext/imageoptimizer/Classes'),
    'MASK\\Mask\\' => array($typo3InstallDir . 'typo3conf/ext/mask/Classes'),
    'NGS\\NgsApproveRequest\\' => array($typo3InstallDir . 'typo3conf/ext/ngs_approve_request/Classes'),
    'NGS\\NgsDefaultTemplate\\' => array($typo3InstallDir . 'typo3conf/ext/ngs_default_template/Classes'),
    'TRITUM\\FormElementLinkedCheckbox\\' => array($typo3InstallDir . 'typo3conf/ext/form_element_linked_checkbox/Classes'),
    'Undefined\\TranslateLocallang\\' => array($typo3InstallDir . 'typo3conf/ext/translate_locallang/Classes'),
    'VV\\T3googleanalytics\\' => array($typo3InstallDir . 'typo3conf/ext/t3googleanalytics/Classes'),
);
